version: '3.9'
services:
  video-downloader:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    container_name: video-downloader
    restart: always
    command: sleep 1000000
    networks:
      docker:
    logging:
      options:
        max-size: 100M

networks:
  docker: